# Generated by Django 5.1.7 on 2025-04-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_vote_book_alter_vote_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='username',
            field=models.CharField(default='Guest', max_length=255),
        ),
    ]
