# Generated by Django 5.1.7 on 2025-04-01 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_vote_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='username',
        ),
    ]
